/*/path_planner:
  ros__parameters:
    pointcloud_topic: "/camera/camera/depth/color/points"

    map_frame: "earth"
    resolution: 0.05

    pointcloud.min_range: 0.0
    pointcloud.max_range: 2.0

    sensor_model.prob_hit: 0.55
    sensor_model.prob_miss: 0.40
    sensor_model.occupancy_threshold: 0.90
    sensor_model.clamping_threshold_max: 0.99

    # Start from an empty map by default.
    map_file: ""

    # Generic fallback output path.
    map_save_path: "new_mapping.bt"

    pose_topic: "/drone0/self_localization/pose"
